### ISSUE TITLE
문서 삭제 시에도 반달로 판단되는 이슈

### ISSUE THREAD

**Issue by jeongjo13** [jeongjo13/imitated-seed-vandalism-block#1]
현재는 문서명과 편집자만 확인하기 때문에 문서를 삭제할 때도 반달로 인식합니다. 이를 해결할 필요가 있습니다.

**Comment by 1ongames** [comment]
그냥 문서:null 에서 반달 발견되면 해당 반달 차단+문서 휴지통화 시키면 될거같은데요

**Comment by jeongjo13** [comment]
휴지통화를 시켜서 아예 키워드 감지 안되게 하는건가요

**Comment by 1ongames** [comment]
그냥 툴 자체에서 api 따와서 문서 이동시키면 될거같습니다

**Comment by 1ongames** [comment]
문서네임은 휴지통:yyyymmdd-hhmmss로 해놓으면 겹칠 문제도 없고요

**Comment by jeongjo13** [comment]
반달 문서 휴지통화 역시 selenium로 할 예정입니다

**Comment by jeongjo13** [comment]
그냥 휴지통화는 랜덤한 난수로 할 예정입니다.
